import { ArrowDownLeft, ArrowUpRight } from 'lucide-react';
import Badge from './Badge';
const statusTone = { success: 'success', successful: 'success', pending: 'reward', failed: 'danger', reversed: 'brand' };
export default function TransactionRow({ title, subtitle, amount, type = 'debit', status, date, icon: CustomIcon, onClick }) {
  const Icon = CustomIcon || (type === 'credit' ? ArrowDownLeft : ArrowUpRight);
  const content = <><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border ${type === 'credit' ? 'border-emerald-200 bg-emerald-100 text-emerald-800 dark:border-emerald-400/20 dark:bg-emerald-400/10 dark:text-emerald-300' : 'border-teal-200 bg-teal-100 text-teal-800 dark:border-teal-400/20 dark:bg-teal-400/10 dark:text-teal-300'}`}><Icon size={19} strokeWidth={2.25} /></span><span className="min-w-0 flex-1 text-left"><span className="block truncate text-sm font-bold text-slate-900 dark:text-slate-100">{title}</span><span className="mt-0.5 block truncate text-xs font-medium text-slate-600 dark:text-slate-400">{subtitle || date}</span></span><span className="text-right"><span className={`block text-sm font-extrabold ${type === 'credit' ? 'text-emerald-700 dark:text-emerald-400' : 'text-slate-900 dark:text-slate-100'}`}>{type === 'credit' ? '+' : '-'}{amount}</span>{status && <Badge tone={statusTone[status.toLowerCase()] || 'neutral'} className="mt-1 capitalize">{status}</Badge>}</span></>;
  const classes = 'my-2 flex w-full items-center gap-3 rounded-2xl border border-slate-200 bg-white px-3 py-3 shadow-[0_3px_12px_rgba(15,23,42,0.05)] transition duration-[var(--ds-duration-fast)] first:mt-0 last:mb-0 hover:border-teal-200 hover:bg-teal-50/40 dark:border-white/10 dark:bg-white/[0.025] dark:shadow-none dark:hover:bg-white/[0.05]';
  return onClick ? <button type="button" className={classes} onClick={onClick}>{content}</button> : <div className={classes}>{content}</div>;
}
